"""
Train MaBrain on conversational dialogues (Capa 4).

Loads dialogues generated by generate_dialogues.py and trains the brain
to follow relational paths in conversational context. Each turn:
  1. Activates the topic entity in Working Memory (WM)
  2. Walks the expected relation path: topic -> expected
  3. Rewards the path (Hebbian reinforcement)
  4. The WM context bias naturally influences future turns

Usage:
    python train_dialogue.py \\
        --brain data/brain_states/brain_massive_v1.json \\
        --dialogues data/processed/layer4_dialogues.jsonl \\
        --output data/brain_states/brain_massive_v1.json \\
        --epochs 3
"""
import json
import os
import sys
import time
from collections import Counter

from braincell import Brain
from working_memory import WorkingMemory


def load_dialogues(path):
    """Load JSONL dialogues file."""
    dialogues = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                dialogues.append(json.loads(line))
    return dialogues


def train_dialogues(brain, dialogues, epochs=3, checkpoint_base=None, reward=0.1):
    """Train brain on multi-turn dialogues."""
    print(f"\n--- Training {len(dialogues)} dialogues ({epochs} epochs, reward={reward}) ---")
    start = time.time()
    total_rewards = 0

    for epoch in range(epochs):
        epoch_start = time.time()
        epoch_rewards = 0
        epoch_correct = 0
        epoch_total = 0

        for dialogue in dialogues:
            turns = dialogue.get("turns", [])
            if not turns:
                continue

            # Fresh WM at start of each dialogue
            brain.wm = WorkingMemory()

            for turn in turns:
                topic = turn.get("topic", "")
                expected = turn.get("expected", "")
                relation = turn.get("relation", "")
                user_text = turn.get("user", "")

                if not topic or not expected or not relation:
                    continue

                # 1. Activate topic in Working Memory (simulates user mentioning it)
                brain.wm.activate_entity(topic, salience=1.0)
                brain.wm.ingest("user", user_text, entities=[topic])

                # 2. Get/create cells
                start_cell = brain.get_or_create_cell(topic)
                target_cell = brain.get_or_create_cell(expected)
                if start_cell.word is None:
                    start_cell.word = topic
                if target_cell.word is None:
                    target_cell.word = expected

                # 3. Walk the expected relation path
                syn = brain.connect(start_cell, target_cell, expected, relation=relation)
                if syn is None:
                    continue

                syn.activation_trace += syn.strength
                syn.inference_usage += 1
                target_cell.activation += syn.strength

                # 4. Reward (Hebbian strengthening)
                brain.reward_thought(reward)
                epoch_rewards += 1

                # 5. Ingest bot response into WM for next turn's context
                brain.wm.ingest("bot", expected, entities=[expected],
                                thought=f"{topic} -> {expected} ({relation})")

                # Check if this relation exists correctly in brain
                epoch_total += 1
                # Verify connection exists
                for s in start_cell.synapses_out:
                    if s.target.id == target_cell.id and s.relation == relation:
                        epoch_correct += 1
                        break

        elapsed_epoch = time.time() - epoch_start
        total_rewards += epoch_rewards
        accuracy = (epoch_correct / epoch_total * 100) if epoch_total > 0 else 0
        print(f"  Epoch {epoch + 1}: {epoch_rewards} turns rewarded, "
              f"accuracy={accuracy:.1f}% ({elapsed_epoch:.1f}s)")
        print(f"    Cells: {len(brain.cells):,}  Synapses: {len(brain.synapses):,}")

        # Save checkpoint
        if checkpoint_base:
            epoch_path = checkpoint_base.replace(".json", f"_dialog_epoch{epoch+1}.json")
            brain.save(epoch_path)
            print(f"    Checkpoint saved: {epoch_path}")

    elapsed = time.time() - start
    print(f"\n  Total: {total_rewards} turns rewarded in {elapsed/60:.1f} min")
    print(f"  Final synapes: {len(brain.synapses):,}")

    return brain


def print_dialogue_test(brain, dialogues):
    """Test the brain on the first few dialogues to see if it knows the paths."""
    print("\n--- Dialogue test (first 3) ---")
    for di, dialogue in enumerate(dialogues[:3]):
        if di >= 3:
            break
        print(f"\n  Dialogue {di + 1}:")
        # Re-run with updated WM to test
        brain.wm = WorkingMemory()
        for turn in dialogue.get("turns", []):
            topic = turn.get("topic", "")
            expected = turn.get("expected", "")
            relation = turn.get("relation", "")

            brain.wm.activate_entity(topic, salience=1.0)
            brain.wm.ingest("user", turn.get("user", ""), entities=[topic])

            # Predict next from topic
            preds = brain.predict_next(topic, top_k=3)
            pred_words = [p[0] for p in preds]
            match = expected in pred_words
            marker = "[OK]" if match else "[NO]"
            top1_match = pred_words[0] == expected if pred_words else False
            top1_marker = "[OK]" if top1_match else "[NO]"

            print(f"    {marker} {turn['user']}")
            print(f"           Expected: {expected} ({relation})")
            print(f"           Predicted: {pred_words[:3]}  top1={top1_marker}")

            brain.wm.ingest("bot", expected, entities=[expected])


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Train MaBrain on conversational dialogues (Capa 4)")
    parser.add_argument("--brain", default="data/brain_states/brain_massive_v1.json",
                        help="Pre-trained brain state to load")
    parser.add_argument("--dialogues", required=True,
                        help="Dialogues JSONL (generated by generate_dialogues.py)")
    parser.add_argument("--output", "-o", default="data/brain_states/brain_massive_v1.json",
                        help="Output brain state path")
    parser.add_argument("--epochs", type=int, default=3,
                        help="Training epochs over dialogues (default: 3)")
    parser.add_argument("--ctx-bias", type=float, default=None,
                        help="Override context_bias_weight (default: keep existing)")
    parser.add_argument("--reward", type=float, default=0.1,
                        help="Reward per dialogue turn (default: 0.1)")
    args = parser.parse_args()

    print("=" * 60)
    print("  MaBrain Conversational Training (Capa 4)")
    print("=" * 60)

    # Load brain
    brain = Brain()
    brain.load(args.brain)
    print(f"\n  Loaded brain: {len(brain.cells):,} cells, {len(brain.synapses):,} synapses")
    print(f"  Context bias weight: {brain.context_bias_weight}")

    if args.ctx_bias is not None:
        brain.context_bias_weight = args.ctx_bias
        print(f"  Override context_bias_weight -> {brain.ctx_bias}")

    # Load dialogues
    dialogues = load_dialogues(args.dialogues)
    total_turns = sum(len(d.get("turns", [])) for d in dialogues)
    print(f"  Loaded {len(dialogues)} dialogues ({total_turns} turns)")

    # Train
    train_dialogues(brain, dialogues, epochs=args.epochs, checkpoint_base=args.output, reward=args.reward)

    # Quick test
    print_dialogue_test(brain, dialogues)

    # Save final brain
    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    brain.save(args.output)
    print(f"\n  Saved trained brain: {args.output} ({os.path.getsize(args.output)/1024/1024:.1f} MB)")
    print("  Done.")


if __name__ == "__main__":
    main()
